export type FormType = {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    linkedin: string;
    portfolio: string;
    position: string;
    salary: string;
    startDate: string;
    resume: File | null;
    coverLetter: File | null;
    personalStatement: string;
    experience: string;
    jobTitle: string;
    employer: string;
    jobDescription: string;
    skills: string;
    certifications: string;
    referenceName: string;
    referenceContact: string;
    relationship: string;
    jobSource: string;
    relocate: boolean;
    workArrangement: string;
};
